apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: default

type: Opaque

stringData:
  POSTGRES_USER: fintrustuser
  POSTGRES_PASSWORD: fintrustpassword
  POSTGRES_DB: fintrust