apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-configmap
  namespace: default

data:
  PORT: "8082"

  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "fintrust"

  CORS_ORIGIN: "http://localhost:5173"
    